name = "persistence-website"
type = "webpack"
route = ''
account_id = '000fde296cba847a78e918414382ba7a'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-06-06"

[env.staging]
route = 'https://staging.persistence.one/*'

[env.release]
route = 'https://persistence.one/*'
